install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.62.1/hugo_0.62.1_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
before_script:
  - rm -rf public
script:
  - hugo
branches:
  only:
    - master